### ISSUE TITLE
assignments link not working, student answers not saving

### ISSUE THREAD

**Issue by Tanaquil18** [RunestoneInteractive/RunestoneServer#1881]
We are new to Runestone, so I apologize for these beginning questions!  But when I (or my students) click on the Assignments link, it brings us to a clickable list of the two assignments I've created so far.  But when I (or they) click on either one of them, it says "Internal Error."

At least one student said that when he just does the questions in context in the book and saves his answers, navigates away, and comes back, they aren't saved.  And I can't see his answers on my end for grading.

**Comment by bnmnetp** [comment]
What is the name of your course?  What is the name of the assignment?  I cannot help you from generalities.

Thanks

**Comment by bnmnetp** [comment]
My guess is that you are using one of our mathbooks and have run into an issue that was reported earlier today, and should be fixed this evening some time.

**Comment by Tanaquil18** [comment]
I am... course is called MTH_333 and is using Beezer's FCLA book as part of the Utmost project.  Sorry about the lack of info!

**Comment by bnmnetp** [comment]
OK, I am just working on pushing out a fix.  I just finished testing it and its good.  I also checked the database and I can assure you that there are answers stored in the database for many reading questions for many of your students.

**Comment by Tanaquil18** [comment]
Oh terrific!  Funny enough, something similar happened with the reading questions in the AIM version of the book last spring that had to be fixed in the first day or two.  

I still don't see the fix yet, and I logged out and back in, but I'll check again in a little bit.  Thank you for your help!

**Comment by bnmnetp** [comment]
It will be this evening when traffic is lower.

**Comment by bnmnetp** [comment]
OK, it is live now.

**Comment by Tanaquil18** [comment]
I see the Assignments links working, and many more student responses than I could see before.  Not the student who emailed me however.  I've emailed him back and told him to try again now.  Hopefully it was something else on his end.

**Comment by Tanaquil18** [comment]
And thank you again!

**Comment by Tanaquil18** [comment]
I've now had another email me that her responses aren't saving.  I checked and can't see them on my end.  She gave an additional clue though, that she's hitting the "grade" button on the bottom of the page and that's when they disappear.

I'll see them in class tomorrow and try to figure out more details about what they're doing as opposed to the other students for whom I can see responses.

**Comment by bnmnetp** [comment]
OK, hopefully we can get to the bottom of it... I have used the grade button on the bottom of the assignment page many times in the last week without a problem.

Again, I think our best source of clues for this will be the Javascript console...

If the answers are really not being saved we should see one of two different messages there

422 - Unprocessable entry  -- in which case there will be details about the data that is not validating that will point me right at the problem.

OR

401 - Unauthorized -- which would mean they are not authenticated to the bookserver. or that their browser is blocking cookies, or ...

of course the 3rd option is that it is something I have not thought of.

I have a bunch of things going on tomorrow, but depending on how it goes and/or what time you meet, I would be happy to zoom in to help debug this.  I know that if it is happening for one student it is happening for 10x that many that have not reported the problem.  Yet I know it is not super widespread based on talking with other instructors...

**Comment by Tanaquil18** [comment]
Class is about to start... I know you're probably busy, but I'll try to keep you updated on what I find out.  I did send you an email from my work account also.

**Comment by bnmnetp** [comment]
So, I just had a video from a student in a different class... Saying essentially the same thing that he does the work, and clicks the button to grade or submit but his answers disappear.  HOWEVER he was not clicking the button to "Load History" which reloads the answers.  That may not be the case for you as you are just doing reading questions??

**Comment by Tanaquil18** [comment]
I didn't see a Load History button when I was helping them today.  But the two who were having trouble seem to have resolved it.  They logged out and back in.  And now their answers seem to be saving and showing up for me.  So I'm not sure what they were doing wrong the first time.  But I think we're up and running now!

**Comment by Tanaquil18** [comment]
Actually, I have a question.  For this book, what's the difference between Reading and Problems?  Does the book measure activity somehow?  There are embedded sage exercises... is it counting interaction with those?  Or does Reading not really apply to us, and I should just assign the Problems that are the Reading Questions?

**Comment by bnmnetp** [comment]
Reading Questions are designed to be formative exercises where your students get points for interacting with the components of each page.  So if your page had 3 multiple choice, 2 fill in the blank, one sage cell and three reflections a reading assignment would give them X points if they interacted with Y of those things -- regardless of whether they got them right or not.   Rob and I are still working on getting PreTeXt books fully integrated so they do not make as much sense for the PreTeXt books just yet, so you are probably better off to stay with Problems where they get points for correctness.

I have a video https://youtu.be/h45c7_wIgGA that does a much better job of explaining that I just did.
